language: go

go:
  - 1.10.x
  - 1.11.x

# make build of forked repos work on travis (the forked repo contents will be
# copied inside the right path)
go_import_path: github.com/sorintlab/sircles

env:
  - TARGET=amd64 GO111MODULE=on
  - TARGET=arm64 GO111MODULE=on

addons:
  apt:
    packages:
    - ldap-utils
    - slapd
  postgresql: "9.6"

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

script:
  # build with webbundle so we'll trigger all the ui build process
  - make
  # TODO(sgotti) temporarily disabled ldap tests
  ##SIRCLES_LDAP_TESTS=1 make test
  - DB_TYPE=postgres PG_CONNSTRING='postgres://postgres@localhost/%s?sslmode=disable' make test
  - DB_TYPE=sqlite3 make test
